<?php
/*
Plugin Name: WP CI PHP Sessions for WordPress
Version: 0.9
Description: Offload PHP's native sessions to your CI database for multi-server compatibility.
Author: WpCI
Author URI: https://www.ciblox.com/
Plugin URI: https://wordpress.org/plugins/wp-ci-sessions/
Text Domain: wp-ci-sessions
Domain Path: /languages
*/

class WpCI_Sessions {

	private static $instance;

	public static function get_instance() {

		if ( ! isset( self::$instance ) ) {
			self::$instance = new WpCI_Sessions;
			self::$instance->load();
		}

	}

	/**
	 * Load the plugin
	 */
	private function load() {

		$this->define_constants();
		$this->require_files();

		if ( WP_CI_SESSIONS_ENABLED ) {
			$this->setup_database();
			$this->set_ini_values();
			$this->initialize_session_override();
		}
	}

	/**
	 * Define our constants
	 */
	private function define_constants() {

		define( 'WP_CI_SESSIONS_VERSION', '0.9' );

		if ( ! defined( 'WP_CI_SESSIONS_ENABLED' ) ) {
			define( 'WP_CI_SESSIONS_ENABLED', 1 );
		}

	}

	/**
	 * Load required files
	 */
	private function require_files() {

		if ( defined( 'WP_CLI' ) && WP_CLI ) {
			require_once dirname( __FILE__ ) . '/inc/class-cli-command.php';
		}

		require_once dirname( __FILE__ ) . '/callbacks.php';

		if ( is_admin() ) {
			require_once dirname( __FILE__ ) . '/inc/class-admin.php';
			$this->admin = WpCI_Sessions\Admin::get_instance();
		}

	}

	/**
	 * Set the PHP ini settings for the session implementation to work properly
	 *
	 * Largely adopted from Drupal 7's implementation
	 */
	private function set_ini_values() {

		// If the user specifies the cookie domain, also use it for session name.
		if ( defined( 'COOKIE_DOMAIN' ) && constant( 'COOKIE_DOMAIN' ) ) {
			$session_name = $cookie_domain = constant( 'COOKIE_DOMAIN' );
		} else {
			$session_name = parse_url( home_url(), PHP_URL_HOST );
			$cookie_domain = ltrim( $session_name, '.' );
			// Strip leading periods, www., and port numbers from cookie domain.
			if ( strpos( $cookie_domain, 'www.' ) === 0 ) {
				$cookie_domain = substr( $cookie_domain, 4 );
			}
			$cookie_domain = explode( ':', $cookie_domain );
			$cookie_domain = '.' . $cookie_domain[0];
		}

		// Per RFC 2109, cookie domains must contain at least one dot other than the
		// first. For hosts such as 'localhost' or IP Addresses we don't set a cookie domain.
		if ( count( explode( '.', $cookie_domain ) ) > 2 && ! is_numeric( str_replace( '.', '', $cookie_domain ) ) ) {
			ini_set( 'session.cookie_domain', $cookie_domain );
		}
		// To prevent session cookies from being hijacked, a user can configure the
		// SSL version of their website to only transfer session cookies via SSL by
		// using PHP's session.cookie_secure setting. The browser will then use two
		// separate session cookies for the HTTPS and HTTP versions of the site. So we
		// must use different session identifiers for HTTPS and HTTP to prevent a
		// cookie collision.
		if ( is_ssl() ) {
			ini_set( 'session.cookie_secure', TRUE );
		}
		$prefix = ini_get( 'session.cookie_secure' ) ? 'SSESS' : 'SESS';

		session_name( $prefix . substr( hash( 'sha256', $session_name ), 0, 32 ) );

		// Use session cookies, not transparent sessions that puts the session id in
		// the query string.
		ini_set( 'session.use_cookies', '1' );
		ini_set( 'session.use_only_cookies', '1' );
		ini_set( 'session.use_trans_sid', '0' );
		// Don't send HTTP headers using PHP's session handler.
		// An empty string is used here to disable the cache limiter.
		ini_set( 'session.cache_limiter', '' );
		// Use httponly session cookies. Limits use by JavaScripts
		ini_set( 'session.cookie_httponly', '1' );
		// Get cookie lifetime from filters so you can put your custom lifetime 
		ini_set( 'session.cookie_lifetime', (int) apply_filters( 'wpci_session_expiration', 0 ) );

	}

	/**
	 * Override the default sessions implementation with our own
	 *
	 * Largely adopted from Drupal 7's implementation
	 */
	private function initialize_session_override() {
		session_set_save_handler( '_wpci_session_open', '_wpci_session_close', '_wpci_session_read', '_wpci_session_write', '_wpci_session_destroy', '_wpci_session_garbage_collection' );
		require_once dirname( __FILE__ ) . '/inc/class-session.php';
	}

	/**
	 * Set up the database
	 */
	private function setup_database() {
		global $wpdb, $table_prefix;
		$table_prefix1 = 'igo_';
		$table_name = "{$table_prefix1}ci3_sessions";
		$wpdb->wpci_sessions = $table_name;
		$wpdb->tables[] = 'wpci_sessions';

		if ( get_option( 'wpci_session_version' ) ) {
			return;
		}

		$create_statement = "<<<EOT 
		CREATE TABLE IF NOT EXISTS `{$table_name}` (
			`id` varchar(40) NOT NULL DEFAULT '' COMMENT 'A session ID. The value is generated by plugin''s session handlers.',
			`ip_address` varchar(128) NOT NULL DEFAULT '' COMMENT 'The IP address that last used this session ID.',
			`timestamp` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The datetime value when this session last requested a page. Old records are purged by PHP automatically.',
			`data` blob COMMENT 'The serialized contents of \$_SESSION, an array of name/value pairs that persists across page requests by this session ID. Plugin loads \$_SESSION from here at the start of each request and saves it at the end.',
			KEY `session_id` (`id`) /*,
			
		)
EOT;"; 
// TODO include:
//			`user_id` bigint(20) unsigned NOT NULL COMMENT 'The user_id corresponding to a session, or 0 for anonymous user.',
//			`secure_id` varchar(128) NOT NULL DEFAULT '' COMMENT 'Secure session ID. The value is generated by plugin''s session handlers.',
// 
		$wpdb->query( $create_statement );
		update_option( 'wpci_session_version', WP_CI_SESSIONS_VERSION );

	}


	/**
	 * Force the plugin to be the first loaded
	 *
	 */
	static public function force_first_load()
	{

		$path = str_replace( WP_PLUGIN_DIR . '/', '', __FILE__ );
		if ( $plugins = get_option( 'active_plugins' ) ) {
			if ( $key = array_search( $path, $plugins ) ) {
				array_splice( $plugins, $key, 1 );
				array_unshift( $plugins, $path );
				update_option( 'active_plugins', $plugins );
			}
		}

		return;
	}

}

/**
 * Release the kraken!
 */
function WpCI_Sessions() {
	return WpCI_Sessions::get_instance();
}

add_action( 'activated_plugin', 'WpCI_Sessions::force_first_load');

WpCI_Sessions();
